- name: check number
  hosts: localhost
  vars_prompt:
  - name: number
    prompt: please enter number
    private: no
  tasks:
  - name: number is less than 10
    ansible.builtin.debug:
      msg: "given number {{ number }} is less than 10"
      when: number < 10
  - name: numbwe ia greater than 10 or equal to 10
    ansible.builtin.debug:
      msg: "given number is {{ number }} is greater than 10 or equal to 10"
      when: number >= 10