- name: variables
  hosts: localhost
  vars:
    course: "Ansible"
    Trainer: "Vinay"
    Duration: "120hrs"
  tasks:
  - name: print information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Vinay}}, Duration is {{Duration}}."