- name: variables
  hosts: localhost
  vars: #variable declaration
    Course: "Terraform"
    Trainer: "Vinay"
    Duration: "15hrs"
  tasks:
  - name: print override information
    vars: #Task level variables
      Course: "DevOps"
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."
  - name: print information 
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."