- name: variables from files
  hosts: localhost
  vars_files: #variable declaration
  - vars.yaml
  tasks:
  - name: print override information
    ansible.builtin.debug:
      msg: "Hi, we are learning {{Course}} from Trainer {{Trainer}}, Duration is {{Duration}}."